### ISSUE TITLE
Querying instead of programming

### ISSUE THREAD

**Issue by romain-malet** [romain-malet/ToulouseMusee#9]
You 're requested the entire list of Musee and adding it in a list if it corresponding to a criteria.
Imagine you have 2 000 000 of museum in your database and a user ask for criteria not matching any museum.
You have to build a query to search with the criteria and this query will return the list of museum corresponding.
Create a method "search(...)" in ServiceMusee, it's its role.

**Comment by romain-malet** [comment]
I will work on this issue

**Comment by Hunsu** [comment]
We are not trying to do something good here. We just doing something that satisfy the users stories. No one have said that there will be 20000000 museums in the database. I have done it like this because it was the simple way for me. 

I think that we have more urgent things to do than redoing something already done!
